set nocompatible
source /usr/share/vim/google/google.vim
filetype plugin indent on
syntax on

call plug#begin('~/.vim/plugged')

" Sensible Default!
Plug 'tpope/vim-sensible'

Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'

call plug#end()

"--------------------------------------------------------------------
" Vim settings {{{
set background=dark
set clipboard=
set completeopt=longest,menuone
set confirm
set colorcolumn=80
set encoding=utf8
set expandtab
set fcs=vert:\|
set fileencoding=utf8
set fileencodings=utf8,iso-8859-1,big5,cp950
set foldmethod=manual
set hidden
set hlsearch
set ignorecase
set incsearch
set lazyredraw
set list
set listchars=tab:»·,trail:·
set mouse=a
set nowrap
set ruler
set scrolloff=5
set sessionoptions-=curdir
set noshiftround
set shiftwidth=2
set showcmd
set smartcase
set smartindent
set softtabstop=2
set synmaxcol=200
set t_Co=256
set tabstop=2
set title
set titleold=
set ttimeoutlen=50
set viewoptions=cursor,folds,slash,unix
set virtualedit=block
set visualbell t_vb=
set wildmenu
set wildignore=*.o,*.so,*.swp,*~,*.pyc

set number
set relativenumber
highlight LineNr ctermfg=grey
nnoremap <C-N> :set number!<CR>:set relativenumber!<CR>

" TODO(Darkpi): See if there's better colorscheme available?
colorscheme torte
" }}}

" Custom keybinding {{{
" Trying space as leader key, need to be careful not conflict with fzf
" bindings.
let mapleader="\<Space>"
let maplocalleader="\<Space>"

" Close buffer without affecting window layout
nnoremap <Leader>q :bp\|bd #<CR>

" Quick load/save
nnoremap <Leader>w :w<CR>
nnoremap <Leader>e :e<CR>

Glug codefmt
Glug codefmt-google
autocmd FileType bzl AutoFormatBuffer buildifier

Glug piper plugin[mappings]
Glug relatedfiles plugin[mappings]

Glug youcompleteme-google
nnoremap <Leader>d :YcmCompleter GoToDeclaration<CR>

" vim-eunuch {{{
" Mappings {{{
cnoremap w!! SudoWrite
" }}}
" }}}

Glug g4

Glug corpweb plugin[mappings]
noremap <unique> <leader>cs :CorpWebCs<Space>

Glug blaze plugin[mappings]='<leader>b'
